# Generated by Django 5.2.15 on 2026-09-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento_motivo_producto_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
